### ISSUE TITLE
Überschrift der Hilfe heißt "Boty hilft dir!"

### ISSUE THREAD

**Issue by Lou-M** [FU-Hagen-Discord/waltraud#6]
![image](https://user-images.githubusercontent.com/73669620/125064843-5ed85080-e0b1-11eb-873b-fa41d5f3143b.png)

Sollte vermutlich "**Waltraud hilft dir!**" heißen.

Funktioniert ansonsten sowohl in den DMs als auch in einem Channel des Psychologie-Servers 👍

**Comment by dnns01** [comment]
Na dann mach doch nen PR 😋
